-- 입양 시각 구하기(2)
-- 프로그래머스 고급 (⭐⭐⭐⭐)
-- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/59413
-- 작성자: 김수인
-- 작성일: 2026. 04. 10. 17:44:44

WITH ETC AS (
    SELECT 0 AS HOUR
UNION ALL SELECT 1
UNION ALL SELECT 2
UNION ALL SELECT 3
UNION ALL SELECT 4
UNION ALL SELECT 5
UNION ALL SELECT 6
UNION ALL SELECT 7
UNION ALL SELECT 8
UNION ALL SELECT 9
UNION ALL SELECT 10
UNION ALL SELECT 11
UNION ALL SELECT 12
UNION ALL SELECT 13
UNION ALL SELECT 14
UNION ALL SELECT 15
UNION ALL SELECT 16
UNION ALL SELECT 17
UNION ALL SELECT 18
UNION ALL SELECT 19
UNION ALL SELECT 20
UNION ALL SELECT 21
UNION ALL SELECT 22
UNION ALL SELECT 23
)
SELECT 
    E.HOUR AS HOUR,
    COUNT(A.ANIMAL_ID) AS COUNT
FROM ETC AS E
LEFT JOIN ANIMAL_OUTS AS A
    ON E.HOUR = HOUR(A.DATETIME)
GROUP BY E.HOUR
ORDER BY HOUR ASC;

-- 모든 시간의 값이 없어서 추가해서 0을 채워 넣어야한다는것 -> CTE를 해야한다는 것
